pipeline {

	agent any

	tools {
		nodejs 'NodeJS_14_11_0'
	}	

	stages {

		stage("build") {
			steps {
				echo 'building the application...'
				sh 'npm cache clean --force'
				sh 'npm install'			
			}
		}

		stage("test") { 
            steps { 
				echo 'testing the application...'
            }
        }

		stage("deploy") { 
            steps { 
				echo 'deploying the application...'
        	}
        }
	}
}
