apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: ratingsweb-hpa
  namespace: ratings-ns
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: ratingsweb-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: ratingsapi-hpa
  namespace: ratings-ns
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: ratingsapi-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50


