apiVersion: v1
kind: Secret
metadata:
  name: ratingsdb-secret
  namespace: ratings-ns
type: Opaque
data:
  ratingsdb_url: "mongodb://${{MONGODB_USERNAME}}:${{MONGODB_PASSWORD}}@${{MONGODB_URL}}:27017/${{MONGDB}}"

---

apiVersion: v1
kind: Secret
metadata:
  name: ratingsdb-secret-lts
  namespace: ratings-ns
type: kubernetes.io/tls
data:
  tls.crt: ${{TLS_CRT}} #base64 encoded cert
  tls.key: ${{TLS_KEY}} #base64 encoded key